In [1]:
import numpy as np
import pandas as pd
import datetime as dt
import random
import string
import hashlib
import json
#Loading data
columns_name = ['id', 'date', 'latitude', 'longitude' ]
df = pd.read_csv('sumission_C', names = columns_name, sep = '\t')

df.head(50)

,id,date,latitude,longitude
0,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:06:00,4.87,45.77
1,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
2,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:40:00,4.87,45.77
3,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
4,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:07:00,4.87,45.77
5,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
6,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
7,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:19:00,4.87,45.77
8,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:16:00,4.87,45.77
9,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
10,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:58:00,4.87,45.77
11,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:17:00,4.87,45.77
12,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:39:00,4.87,45.77
13,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
14,DEL,2015-03-04 00:39:00,4.87,45.77
15,DEL,2015-03-04 00:39:00,4.87,45.77
16,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:15:00,4.87,45.77
17,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:59:00,4.87,45.77
18,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:38:00,4.87,45.77
19,DEL,2015-03-04 00:07:00,4.87,45.77
20,DEL,2015-03-04 00:38:00,4.87,45.77
21,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:32:00,4.87,45.77
22,DEL,2015-03-04 00:32:00,4.87,45.77
23,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:50:00,4.87,45.77
24,DEL,2015-03-04 00:16:00,4.87,45.77
25,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:41:00,4.87,45.77
26,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:09:00,4.87,45.77
27,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:24:00,4.87,45.77
28,DEL,2015-03-04 00:17:00,4.87,45.77
29,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
30,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:37:00,4.87,45.77
31,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:48:00,4.87,45.77
32,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
33,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
34,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:35:00,4.87,45.77
35,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
36,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
37,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:21:00,4.87,45.77
38,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
39,DEL,2015-03-04 00:48:00,4.87,45.77
40,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-03 00:29:00,4.87,45.77
41,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:46:00,4.87,45.77
42,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:14:00,4.87,45.77
43,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:28:00,4.87,45.77
44,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:52:00,4.87,45.77
45,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:55:00,4.87,45.77
46,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:56:00,4.87,45.77
47,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:31:00,4.87,45.77
48,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:08:00,4.87,45.77
49,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:18:00,4.87,45.77

In [21]:
df.head(50)

,id,date,latitude,longitude
0,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:06:00,4.87,45.77
1,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:10:00,4.87,45.77
2,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:40:00,4.87,45.77
3,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:44:00,4.87,45.77
4,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:07:00,4.87,45.77
5,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:49:00,4.87,45.77
6,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:26:00,4.87,45.77
7,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:19:00,4.87,45.77
8,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:16:00,4.87,45.77
9,NaN,2015-03-04 00:10:00,4.87,45.77
10,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:58:00,4.87,45.77
11,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:17:00,4.87,45.77
12,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:39:00,4.87,45.77
13,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:11:00,4.87,45.77
14,DEL,2015-03-04 00:39:00,4.87,45.77
15,DEL,2015-03-04 00:39:00,4.87,45.77
16,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:15:00,4.87,45.77
17,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:59:00,4.87,45.77
18,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:38:00,4.87,45.77
19,DEL,2015-03-04 00:07:00,4.87,45.77
20,DEL,2015-03-04 00:38:00,4.87,45.77
21,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:32:00,4.87,45.77
22,DEL,2015-03-04 00:32:00,4.87,45.77
23,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:50:00,4.87,45.77
24,DEL,2015-03-04 00:16:00,4.87,45.77
25,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:41:00,4.87,45.77
26,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:09:00,4.87,45.77
27,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:24:00,4.87,45.77
28,DEL,2015-03-04 00:17:00,4.87,45.77
29,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:22:00,4.87,45.77
30,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:37:00,4.87,45.77
31,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:48:00,4.87,45.77
32,NaN,2015-03-04 00:11:00,4.87,45.77
33,NaN,2015-03-04 00:49:00,4.87,45.77
34,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:35:00,4.87,45.77
35,NaN,2015-03-04 00:44:00,4.87,45.77
36,NaN,2015-03-04 00:26:00,4.87,45.77
37,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:21:00,4.87,45.77
38,NaN,2015-03-04 00:22:00,4.87,45.77
39,DEL,2015-03-04 00:48:00,4.87,45.77
40,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-03 00:29:00,4.87,45.77
41,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:46:00,4.87,45.77
42,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:14:00,4.87,45.77
43,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:28:00,4.87,45.77
44,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:52:00,4.87,45.77
45,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:55:00,4.87,45.77
46,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:56:00,4.87,45.77
47,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:31:00,4.87,45.77
48,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:08:00,4.87,45.77
49,b2a073897ed6dcda315e94492a0db9423715cbe559cbca...,2015-03-04 00:18:00,4.87,45.77

In [2]:
import numpy as np
import pandas as pd
import datetime as dt
import random
import string
import hashlib
import json
#Loading data
columns_name = ['id', 'date', 'latitude', 'longitude' ]
anon = pd.read_csv('test', names = columns_name, sep = '\t')

anon.head(50)

     id                 date  latitude  longitude
0     1  2015-03-04 00:06:00      4.87      45.77
1     1  2015-03-04 00:10:00      4.87      45.77
2     1  2015-03-04 00:40:00      4.87      45.77
3     1  2015-03-04 00:44:00      4.87      45.77
4     1  2015-03-04 00:07:00      4.87      45.77
5     1  2015-03-04 00:49:00      4.87      45.77
6     1  2015-03-04 00:26:00      4.87      45.77
7     1  2015-03-04 00:19:00      4.87      45.77
8     1  2015-03-04 00:16:00      4.87      45.77
9     1  2015-03-04 00:10:00      4.87      45.77
10    1  2015-03-04 00:58:00      4.87      45.77
11    1  2015-03-04 00:17:00      4.87      45.77
12    1  2015-03-04 00:39:00      4.87      45.77
13    1  2015-03-04 00:11:00      4.87      45.77
14  DEL  2015-03-04 00:39:00      4.87      45.77
15  DEL  2015-03-04 00:39:00      4.87      45.77
16    1  2015-03-04 00:15:00      4.87      45.77
17    1  2015-03-04 00:59:00      4.87      45.77
18    1  2015-03-04 00:38:00      4.87      45.77
19  DEL  2015-03-04 00:07:00      4.87      45.77
20  DEL  2015-03-04 00:38:00      4.87      45.77
21    1  2015-03-04 00:32:00      4.87      45.77
22  DEL  2015-03-04 00:32:00      4.87      45.77
23    1  2015-03-04 00:50:00      4.87      45.77
24  DEL  2015-03-04 00:16:00      4.87      45.77
25    1  2015-03-04 00:41:00      4.87      45.77
26    1  2015-03-04 00:09:00      4.87      45.77
27    1  2015-03-04 00:24:00      4.87      45.77
28  DEL  2015-03-04 00:17:00      4.87      45.77
29    1  2015-03-04 00:22:00      4.87      45.77
30    1  2015-03-04 00:37:00      4.87      45.77
31    1  2015-03-04 00:48:00      4.87      45.77
32    1  2015-03-04 00:11:00      4.87      45.77
33    1  2015-03-04 00:49:00      4.87      45.77
34    1  2015-03-04 00:35:00      4.87      45.77
35    1  2015-03-04 00:44:00      4.87      45.77
36    1  2015-03-04 00:26:00      4.87      45.77
37    1  2015-03-04 00:21:00      4.87      45.77
38    1  2015-03-04 00:22:00      4.87      45.77
39  DEL  2015-03-04 00:48:00      4.87      45.77
40    1  2015-03-04 00:29:00      4.87      45.77
41    1  2015-03-04 00:46:00      4.87      45.77
42    1  2015-03-04 00:14:00      4.87      45.77
43    1  2015-03-04 00:28:00      4.87      45.77
44    1  2015-03-04 00:52:00      4.87      45.77
45    1  2015-03-04 00:55:00      4.87      45.77
46    1  2015-03-04 00:56:00      4.87      45.77
47    1  2015-03-04 00:31:00      4.87      45.77
48    1  2015-03-04 00:08:00      4.87      45.77
49    1  2015-03-04 00:18:00      4.87      45.77

In [3]:
df['date'] = anon['date']

df.head(50)

,id,date,latitude,longitude
0,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:06:00,4.87,45.77
1,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
2,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:40:00,4.87,45.77
3,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
4,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:07:00,4.87,45.77
5,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
6,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
7,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:19:00,4.87,45.77
8,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:16:00,4.87,45.77
9,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
10,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:58:00,4.87,45.77
11,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:17:00,4.87,45.77
12,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:39:00,4.87,45.77
13,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
14,DEL,2015-03-04 00:39:00,4.87,45.77
15,DEL,2015-03-04 00:39:00,4.87,45.77
16,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:15:00,4.87,45.77
17,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:59:00,4.87,45.77
18,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:38:00,4.87,45.77
19,DEL,2015-03-04 00:07:00,4.87,45.77
20,DEL,2015-03-04 00:38:00,4.87,45.77
21,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:32:00,4.87,45.77
22,DEL,2015-03-04 00:32:00,4.87,45.77
23,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:50:00,4.87,45.77
24,DEL,2015-03-04 00:16:00,4.87,45.77
25,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:41:00,4.87,45.77
26,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:09:00,4.87,45.77
27,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:24:00,4.87,45.77
28,DEL,2015-03-04 00:17:00,4.87,45.77
29,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
30,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:37:00,4.87,45.77
31,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:48:00,4.87,45.77
32,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
33,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
34,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:35:00,4.87,45.77
35,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
36,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
37,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:21:00,4.87,45.77
38,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
39,DEL,2015-03-04 00:48:00,4.87,45.77
40,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:29:00,4.87,45.77
41,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:46:00,4.87,45.77
42,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:14:00,4.87,45.77
43,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:28:00,4.87,45.77
44,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:52:00,4.87,45.77
45,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:55:00,4.87,45.77
46,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:56:00,4.87,45.77
47,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:31:00,4.87,45.77
48,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:08:00,4.87,45.77
49,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:18:00,4.87,45.77

In [4]:
df['date'] = df['date'].str.slice(stop = 16)
df['date'] = pd.to_datetime(df['date'], format = "%Y-%m-%d %H:%M")

#df['hour'] = df['date'].dt.hour
#df['day'] = df['date'].dt.day
df['week'] = df['date'].dt.isocalendar().week

In [7]:
#Change date to random (be the same week)
def change_date(date):
    rand_day = int(np.random.choice([0,1], p=[0.999, 0.001]))
    return date - dt.timedelta(days=rand_day) if date.isocalendar()[1] == (date - dt.timedelta(days=rand_day)).isocalendar()[1] else date + dt.timedelta(days=rand_day)

In [8]:
df.loc[df['id'] != 'DEL', 'date'] = df.loc[df['id'] != 'DEL', 'date'].apply(change_date)

In [5]:
df['week'] = df['date'].dt.isocalendar().week
id_time = df.loc[df['id']!= 'DEL',['id', 'date', 'latitude', 'longitude','week']]
id_time['new_id'] =  str(random.randrange(10000,19999)) + id_time['id'].astype(str) + id_time['week'].astype(str) +str(random.randrange(10000,19999))

id_time['new_id'] = id_time['new_id'].apply(lambda x: hashlib.sha256(x.encode()).hexdigest())
df.loc[df['id'] != 'DEL', 'id'] = id_time['new_id']

In [6]:
print(id_time.head(50))

   id                date  latitude  longitude  week  \
0   1 2015-03-04 00:06:00      4.87      45.77    10
1   1 2015-03-04 00:10:00      4.87      45.77    10
2   1 2015-03-04 00:40:00      4.87      45.77    10
3   1 2015-03-04 00:44:00      4.87      45.77    10
4   1 2015-03-04 00:07:00      4.87      45.77    10
5   1 2015-03-04 00:49:00      4.87      45.77    10
6   1 2015-03-04 00:26:00      4.87      45.77    10
7   1 2015-03-04 00:19:00      4.87      45.77    10
8   1 2015-03-04 00:16:00      4.87      45.77    10
9   1 2015-03-04 00:10:00      4.87      45.77    10
10  1 2015-03-04 00:58:00      4.87      45.77    10
11  1 2015-03-04 00:17:00      4.87      45.77    10
12  1 2015-03-04 00:39:00      4.87      45.77    10
13  1 2015-03-04 00:11:00      4.87      45.77    10
16  1 2015-03-04 00:15:00      4.87      45.77    10
17  1 2015-03-04 00:59:00      4.87      45.77    10
18  1 2015-03-04 00:38:00      4.87      45.77    10
21  1 2015-03-04 00:32:00      4.87      45.77    10
23  1 2015-03-04 00:50:00      4.87      45.77    10
25  1 2015-03-04 00:41:00      4.87      45.77    10
26  1 2015-03-04 00:09:00      4.87      45.77    10
27  1 2015-03-04 00:24:00      4.87      45.77    10
29  1 2015-03-04 00:22:00      4.87      45.77    10
30  1 2015-03-04 00:37:00      4.87      45.77    10
31  1 2015-03-04 00:48:00      4.87      45.77    10
32  1 2015-03-04 00:11:00      4.87      45.77    10
33  1 2015-03-04 00:49:00      4.87      45.77    10
34  1 2015-03-04 00:35:00      4.87      45.77    10
35  1 2015-03-04 00:44:00      4.87      45.77    10
36  1 2015-03-04 00:26:00      4.87      45.77    10
37  1 2015-03-04 00:21:00      4.87      45.77    10
38  1 2015-03-04 00:22:00      4.87      45.77    10
40  1 2015-03-03 00:29:00      4.87      45.77    10
41  1 2015-03-04 00:46:00      4.87      45.77    10
42  1 2015-03-04 00:14:00      4.87      45.77    10
43  1 2015-03-04 00:28:00      4.87      45.77    10
44  1 2015-03-04 00:52:00      4.87      45.77    10
45  1 2015-03-04 00:55:00      4.87      45.77    10
46  1 2015-03-04 00:56:00      4.87      45.77    10
47  1 2015-03-04 00:31:00      4.87      45.77    10
48  1 2015-03-04 00:08:00      4.87      45.77    10
49  1 2015-03-04 00:18:00      4.87      45.77    10
50  1 2015-03-04 00:37:00      4.87      45.77    10
52  1 2015-03-04 00:52:00      4.87      45.77    10
53  1 2015-03-04 00:46:00      4.87      45.77    10
54  1 2015-03-04 00:48:00      4.87      45.77    10
55  1 2015-03-04 00:41:00      4.87      45.77    10
56  1 2015-03-04 00:17:00      4.87      45.77    10
57  1 2015-03-04 00:25:00      4.87      45.77    10
58  1 2015-03-04 00:32:00      4.87      45.77    10

                                               new_id
0   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
1   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
2   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
3   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
4   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
5   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
6   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
7   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
8   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
9   3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
10  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
11  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
12  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
13  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
16  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
17  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
18  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
21  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
23  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
25  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
26  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
27  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
29  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
30  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
31  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
32  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
33  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
34  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
35  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
36  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
37  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
38  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
40  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
41  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
42  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
43  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
44  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
45  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
46  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
47  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
48  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
49  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
50  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
52  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
53  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
54  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
55  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
56  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
57  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...
58  3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...

In [10]:
# Drop 2 columns 'week' and 'new_week'
#df.drop(['week'], inplace=True, axis=1)

#Save file 
df.to_csv('sumission_C',index = False, header=False, columns = None, sep='\t')
#df.head()

In [9]:
a = df.loc[df.id!= 'DEL'].count()
a

id           25758638
date         25758638
latitude     25758638
longitude    25758638
dtype: int64

In [10]:
a = anon.loc[anon.id!= 'DEL'].count()
a

id           25758638
date         25758638
latitude     25758638
longitude    25758638
dtype: int64

In [6]:
df.head(50)

,id,date,latitude,longitude
0,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:06:00,4.87,45.77
1,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
2,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:40:00,4.87,45.77
3,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
4,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:07:00,4.87,45.77
5,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
6,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
7,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:19:00,4.87,45.77
8,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:16:00,4.87,45.77
9,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:10:00,4.87,45.77
10,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:58:00,4.87,45.77
11,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:17:00,4.87,45.77
12,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:39:00,4.87,45.77
13,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
14,DEL,2015-03-04 00:39:00,4.87,45.77
15,DEL,2015-03-04 00:39:00,4.87,45.77
16,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:15:00,4.87,45.77
17,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:59:00,4.87,45.77
18,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:38:00,4.87,45.77
19,DEL,2015-03-04 00:07:00,4.87,45.77
20,DEL,2015-03-04 00:38:00,4.87,45.77
21,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:32:00,4.87,45.77
22,DEL,2015-03-04 00:32:00,4.87,45.77
23,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:50:00,4.87,45.77
24,DEL,2015-03-04 00:16:00,4.87,45.77
25,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:41:00,4.87,45.77
26,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:09:00,4.87,45.77
27,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:24:00,4.87,45.77
28,DEL,2015-03-04 00:17:00,4.87,45.77
29,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
30,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:37:00,4.87,45.77
31,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:48:00,4.87,45.77
32,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:11:00,4.87,45.77
33,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:49:00,4.87,45.77
34,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:35:00,4.87,45.77
35,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:44:00,4.87,45.77
36,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:26:00,4.87,45.77
37,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:21:00,4.87,45.77
38,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:22:00,4.87,45.77
39,DEL,2015-03-04 00:48:00,4.87,45.77
40,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:29:00,4.87,45.77
41,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:46:00,4.87,45.77
42,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:14:00,4.87,45.77
43,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:28:00,4.87,45.77
44,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:52:00,4.87,45.77
45,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:55:00,4.87,45.77
46,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:56:00,4.87,45.77
47,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:31:00,4.87,45.77
48,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:08:00,4.87,45.77
49,3fa0ac218027ffb316252e0b27ce8726f11042357ac37c...,2015-03-04 00:18:00,4.87,45.77